# Generated by Django 4.2.7 on 2023-11-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='catalog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.catalog', verbose_name='Каталог'),
        ),
    ]
